"""Changed type of amount from integer to decimal

Revision ID: 6005816cef2f
Revises: b878bcb20ad1
Create Date: 2025-03-24 16:32:07.006619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6005816cef2f'
down_revision: Union[str, None] = 'b878bcb20ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('convertion_history', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('convertion_history', 'amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
